version: 2
jobs:
  deploy_dev: # ジョブ名
    docker:
      - image: circleci/node:9.11.2 # ジョブ実行環境のDockerイメージを記述
    steps:
      - checkout
      - attach_workspace:
        at: docs/_build
      - run:
        name: Install and configure dependencies
        command: |
          npm install -g --silent gh-pages@2.0.1
          git config user.email "ci-build@nekodango"
          git config user.name "ci-build"
      - run:
          name: Deploy docs to gh-pages branch
          command: gh-pages --dist docs/_build/dist
workflows:
  version: 2
  deploy_dev: # ワークフローの名前
    jobs:
      - deploy_dev: # 上で定義したジョブを指定します
          filters:
            branches:
              only: master # developブランチのみを実行対象とします
